# Generated by Django 3.0 on 2019-12-09 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(max_length=50)),
                ('programCategory', models.CharField(max_length=50)),
                ('athleteName', models.CharField(max_length=50)),
                ('athletePhoto', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('day', models.IntegerField(max_length=2, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('list_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_title', models.CharField(max_length=50)),
                ('ex1', models.CharField(max_length=50)),
                ('ex2', models.CharField(max_length=50)),
                ('ex3', models.CharField(max_length=50)),
                ('ex4', models.CharField(blank=True, max_length=50)),
                ('ex5', models.CharField(blank=True, max_length=50)),
                ('ex6', models.CharField(blank=True, max_length=50)),
                ('ex7', models.CharField(blank=True, max_length=50)),
                ('reps1', models.CharField(max_length=25)),
                ('reps2', models.CharField(max_length=25)),
                ('reps3', models.CharField(max_length=25)),
                ('reps4', models.CharField(blank=True, max_length=25)),
                ('reps5', models.CharField(blank=True, max_length=25)),
                ('reps6', models.CharField(blank=True, max_length=25)),
                ('reps7', models.CharField(blank=True, max_length=25)),
                ('for_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_day', to='trainingprograms.Programs', to_field='day')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprograms.Programs')),
            ],
        ),
    ]
