# Generated by Django 3.0 on 2019-12-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(check=models.Q(for_day__gt=0), name='for_day_gt_0'),
        ),
    ]
