# Generated by Django 3.0 on 2019-12-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='day',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
