# Generated by Django 3.0 on 2019-12-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0002_auto_20191209_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='slug_athlete',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='slug_program',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
