# Generated by Django 3.0 on 2019-12-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0002_auto_20191209_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='published',
            new_name='is_published',
        ),
    ]
