# Generated by Django 3.0 on 2019-12-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0003_auto_20191211_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='slug_athlete',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='slug_program',
        ),
    ]
