# Generated by Django 3.0 on 2019-12-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0004_auto_20191211_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='athleteName',
            new_name='athlete_name',
        ),
        migrations.RenameField(
            model_name='programs',
            old_name='athletePhoto',
            new_name='athlete_photo',
        ),
        migrations.RenameField(
            model_name='programs',
            old_name='programCategory',
            new_name='program_category',
        ),
        migrations.RenameField(
            model_name='programs',
            old_name='programName',
            new_name='program_name',
        ),
        migrations.AlterField(
            model_name='programs',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
