# Generated by Django 3.0 on 2019-12-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0005_auto_20191211_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
