# Generated by Django 3.0 on 2019-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0006_auto_20191212_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(check=models.Q(for_day__lte=7), name='for_day_lte_7'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(check=models.Q(week__gt=0), name='week_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(check=models.Q(week__lte=9), name='week_lte_9'),
        ),
    ]
