# Generated by Django 3.0 on 2019-12-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0010_auto_20191217_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
