# Generated by Django 3.0 on 2019-12-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprograms', '0013_auto_20191221_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='users',
        ),
    ]
