# Generated by Django 3.0 on 2019-12-23 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainingprograms', '0014_auto_20191223_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprograms.Programs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='programs',
            name='users',
            field=models.ManyToManyField(blank=True, through='trainingprograms.Program_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
